#!/usr/bin/env python3
"""Generates sha512_nway.h: fully unrolled, N-way interleaved SHA-512 compression functions
(ARMv8.2 SHA-512 intrinsics). Statements of the N independent streams are interleaved so the
CPU overlaps their dependency chains. Operand layout verified against a scalar reference and
OpenSSL (blmc --selftest). Usage: python3 gen_nway.py > sha512_nway.h"""
def gen(N):
    L=[f"static void sha512_compress_x{N}(uint64_t (*st)[8], const uint8_t (*blk)[128]) {{"]
    for j in range(N):
        L.append(f"    uint64x2_t ab{j}=vld1q_u64(st[{j}]), cd{j}=vld1q_u64(st[{j}]+2), ef{j}=vld1q_u64(st[{j}]+4), gh{j}=vld1q_u64(st[{j}]+6);")
        L.append(f"    const uint64x2_t A{j}=ab{j}, C{j}=cd{j}, E{j}=ef{j}, G{j}=gh{j}; uint64x2_t s{j}, t{j}, n{j};")
        for i in range(8): L.append(f"    uint64x2_t m{j}_{i}=vreinterpretq_u64_u8(vrev64q_u8(vld1q_u8(blk[{j}]+{16*i})));")
    for r in range(0,80,2):
        i=(r//2)&7
        if r>=16 and i==0:           # advance the message schedule by 16 words
            for q in range(8):
                for j in range(N):
                    L.append(f"    m{j}_{q}=vsha512su1q_u64(vsha512su0q_u64(m{j}_{q},m{j}_{(q+1)&7}),m{j}_{(q+7)&7},vextq_u64(m{j}_{(q+4)&7},m{j}_{(q+5)&7},1));")
        for j in range(N): L.append(f"    s{j}=vaddq_u64(m{j}_{i},vld1q_u64(K512+{r})); s{j}=vaddq_u64(vextq_u64(s{j},s{j},1),gh{j});")
        for j in range(N): L.append(f"    t{j}=vsha512hq_u64(s{j},vextq_u64(ef{j},gh{j},1),vextq_u64(cd{j},ef{j},1));")
        for j in range(N): L.append(f"    n{j}=vsha512h2q_u64(t{j},cd{j},ab{j}); gh{j}=ef{j}; ef{j}=vaddq_u64(cd{j},t{j}); cd{j}=ab{j}; ab{j}=n{j};")
    for j in range(N):
        L.append(f"    vst1q_u64(st[{j}],vaddq_u64(ab{j},A{j})); vst1q_u64(st[{j}]+2,vaddq_u64(cd{j},C{j})); vst1q_u64(st[{j}]+4,vaddq_u64(ef{j},E{j})); vst1q_u64(st[{j}]+6,vaddq_u64(gh{j},G{j}));")
    L.append("}")
    return "\n".join(L)
if __name__ == "__main__":
    print("/* GENERATED by gen_nway.py - do not edit. N-way interleaved, fully unrolled SHA-512 compress. */")
    for n in (1, 2, 4): print(gen(n))
